<a href="https://colab.research.google.com/github/NomNomNarang/DeepLearning/blob/main/dropOutRegularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##PRECISION AND RECALL
##accuracy->total correct from whole sample
##precision->out of all dog predictions how many you got right?
##recall->out of all dog samples how many you got right?

##CONFUSION MATRIX

In [ ]:
##DROPOUT REGULARIZATION:OVERFIITING AND UNDERFITTING
##dropout helps with overfitting as it might dropped out at random
##neurons will not lear redundant details of inputs

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [3]:
df=pd.read_csv('sonar_dataset.csv')
df.head()

0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032  R
0  0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044  R
1  0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078  R
2  0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117  R
3  0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094  R
4  0.0286  0.0453  0.0277  0.0174  0.0384  ...  0.0057  0.0027  0.0051  0.0062  R

[5 rows x 61 columns]

In [4]:
df.shape

(207, 61)

In [5]:
df.isna().isnull()

0.0200  0.0371  0.0428  0.0207  ...  0.0084  0.0090  0.0032      R
0     False   False   False   False  ...   False   False   False  False
1     False   False   False   False  ...   False   False   False  False
2     False   False   False   False  ...   False   False   False  False
3     False   False   False   False  ...   False   False   False  False
4     False   False   False   False  ...   False   False   False  False
..      ...     ...     ...     ...  ...     ...     ...     ...    ...
202   False   False   False   False  ...   False   False   False  False
203   False   False   False   False  ...   False   False   False  False
204   False   False   False   False  ...   False   False   False  False
205   False   False   False   False  ...   False   False   False  False
206   False   False   False   False  ...   False   False   False  False

[207 rows x 61 columns]

In [6]:
df.columns

Index(['0.0200', '0.0371', '0.0428', '0.0207', '0.0954', '0.0986', '0.1539',
       '0.1601', '0.3109', '0.2111', '0.1609', '0.1582', '0.2238', '0.0645',
       '0.0660', '0.2273', '0.3100', '0.2999', '0.5078', '0.4797', '0.5783',
       '0.5071', '0.4328', '0.5550', '0.6711', '0.6415', '0.7104', '0.8080',
       '0.6791', '0.3857', '0.1307', '0.2604', '0.5121', '0.7547', '0.8537',
       '0.8507', '0.6692', '0.6097', '0.4943', '0.2744', '0.0510', '0.2834',
       '0.2825', '0.4256', '0.2641', '0.1386', '0.1051', '0.1343', '0.0383',
       '0.0324', '0.0232', '0.0027', '0.0065', '0.0159', '0.0072', '0.0167',
       '0.0180', '0.0084', '0.0090', '0.0032', 'R'],
      dtype='object')

In [9]:
df['R'].value_counts()

R
M    111
R     96
Name: count, dtype: int64

In [18]:
df1=df

In [19]:
df1=df.replace({'R': {'R':1,'M':0}})

/tmp/ipython-input-1435903570.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1=df.replace({'R': {'R':1,'M':0}})


In [20]:
df1['R']

0      1
1      1
2      1
3      1
4      1
      ..
202    0
203    0
204    0
205    0
206    0
Name: R, Length: 207, dtype: int64

In [21]:
x=df1.drop('R',axis=1)
y=df1['R']
x

0.0200  0.0371  0.0428  0.0207  ...  0.0180  0.0084  0.0090  0.0032
0    0.0453  0.0523  0.0843  0.0689  ...  0.0140  0.0049  0.0052  0.0044
1    0.0262  0.0582  0.1099  0.1083  ...  0.0316  0.0164  0.0095  0.0078
2    0.0100  0.0171  0.0623  0.0205  ...  0.0050  0.0044  0.0040  0.0117
3    0.0762  0.0666  0.0481  0.0394  ...  0.0072  0.0048  0.0107  0.0094
4    0.0286  0.0453  0.0277  0.0174  ...  0.0057  0.0027  0.0051  0.0062
..      ...     ...     ...     ...  ...     ...     ...     ...     ...
202  0.0187  0.0346  0.0168  0.0177  ...  0.0065  0.0115  0.0193  0.0157
203  0.0323  0.0101  0.0298  0.0564  ...  0.0034  0.0032  0.0062  0.0067
204  0.0522  0.0437  0.0180  0.0292  ...  0.0140  0.0138  0.0077  0.0031
205  0.0303  0.0353  0.0490  0.0608  ...  0.0034  0.0079  0.0036  0.0048
206  0.0260  0.0363  0.0136  0.0272  ...  0.0040  0.0036  0.0061  0.0115

[207 rows x 60 columns]

In [22]:
y

0      1
1      1
2      1
3      1
4      1
      ..
202    0
203    0
204    0
205    0
206    0
Name: R, Length: 207, dtype: int64

In [29]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)


In [30]:
x_train.shape,x_test.shape

((165, 60), (42, 60))

In [56]:
modeld=keras.Sequential([
    keras.layers.Dense(60,input_shape=(60,),activation='relu'),
    keras.layers.Dense(30,activation='relu'),
    keras.layers.Dense(15,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])
modeld.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

modeld.fit(x_train,y_train,epochs=100,batch_size=8)

Epoch 1/100


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5356 - loss: 0.6980
Epoch 2/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6313 - loss: 0.6520 
Epoch 3/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6455 - loss: 0.6233 
Epoch 4/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7488 - loss: 0.5669 
Epoch 5/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7586 - loss: 0.5270 
Epoch 6/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7473 - loss: 0.5263 
Epoch 7/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7691 - loss: 0.4685 
Epoch 8/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7976 - loss: 0.4376 
Epoch 9/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8676 - loss: 0.3859 
Epoch 10/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7750 - loss: 0.4142 
Epoch 11/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8626 - loss: 0.3559 
Epoch 12/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0

In [33]:
y_train.shape

(165,)

In [57]:
modeld.evaluate(x_test,y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8105 - loss: 1.4185 


[1.4119535684585571, 0.8095238208770752]

In [58]:
y_predict=modeld.predict(x_test)
y_predict

##round off the values
y_predict=np.round(y_predict)
y_predict

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.]], dtype=float32)

In [39]:
y_test

161    0
15     1
73     1
96     0
166    0
9      1
100    0
135    0
18     1
148    0
171    0
30     1
155    0
205    0
125    0
196    0
164    0
189    0
84     1
75     1
124    0
170    0
104    0
101    0
69     1
25     1
95     1
16     1
141    0
184    0
154    0
68     1
66     1
120    0
147    0
98     0
138    0
167    0
45     1
113    0
65     1
177    0
Name: R, dtype: int64

In [46]:
y_predict[0
          ]

array([0.], dtype=float32)

In [52]:
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test,y_predict)) ## y_true=y_test , y_pred=y_lables

              precision    recall  f1-score   support

           0       0.88      0.81      0.85        27
           1       0.71      0.80      0.75        15

    accuracy                           0.81        42
   macro avg       0.79      0.81      0.80        42
weighted avg       0.82      0.81      0.81        42



In [59]:
##introducing dropout layers
model=keras.Sequential([
    keras.layers.Dense(60,input_shape=(60,),activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30,activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15,activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1,activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train,y_train,epochs=100,batch_size=8)

Epoch 1/100


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


21/21 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.4767 - loss: 0.7572
Epoch 2/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4567 - loss: 0.7087
Epoch 3/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5972 - loss: 0.6929 
Epoch 4/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4401 - loss: 0.7175 
Epoch 5/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4476 - loss: 0.7119 
Epoch 6/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5155 - loss: 0.6998 
Epoch 7/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4409 - loss: 0.6994
Epoch 8/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5833 - loss: 0.6800 
Epoch 9/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5492 - loss: 0.6959 
Epoch 10/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4678 - loss: 0.7093 
Epoch 11/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5883 - loss: 0.6752
Epoch 12/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.57

In [62]:
model.evaluate(x_test,y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7842 - loss: 0.5406


[0.5591017007827759, 0.7857142686843872]

In [66]:
y_pred=model.predict(x_test)
y_pred
y_pred=np.round(y_pred)
y_pred

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step 


array([[0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.]], dtype=float32)

In [68]:
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.78      0.82        27
           1       0.67      0.80      0.73        15

    accuracy                           0.79        42
   macro avg       0.77      0.79      0.78        42
weighted avg       0.80      0.79      0.79        42

